project:
  type: website

website:
  title: "Jiayang Gu's personal website"
  navbar:
    title: "jiayang<br>gu"
    right:
      - href: index.qmd
        text: HOME
      - href: research.qmd
        text: RESEARCH
      - href: teaching.qmd
        text: TEACHING
      - href: cv.qmd
        text: CV
      - href: blog/index.qmd
        text: BLOG

  # favicon: icon-32.png
        
format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    link-external-newwindow: true
    metadata:
      pagetitle: "Jiayang Gu"

editor: source

execute:
  freeze: auto